ci: support macos in "install-cometbft" script
Flagged by @TalDerei as a nice-to-have during a recent pairing session.
Closes #4264.

diff --git a/deployments/scripts/install-cometbft b/deployments/scripts/install-cometbft
--- a/deployments/scripts/install-cometbft
+++ b/deployments/scripts/install-cometbft
@@ -7,26 +7,38 @@ set -euo pipefail
 # Sane defaults
 COMETBFT_VERSION="${COMETBFT_VERSION:-0.37.5}"
 
+# Determine platform, so we can support both macOS and Linux.
+uname_kernel="$(uname -s)"
+uname_machine="$(uname -m)"
+if [[ "$uname_kernel" = "Linux" && "$uname_machine" = "x86_64" ]] ; then
+    platform_string="linux_amd64"
+elif [[ "$uname_kernel" = "Darwin" && "$uname_machine" = "x86_64" ]] ; then
+    platform_string="darwin_amd64"
+elif [[ "$uname_kernel" = "Darwin" && "$uname_machine" = "arm64" ]] ; then
+    platform_string="darwin_arm64"
+else
+    >&2 echo "ERROR: platform '$uname_kernel' with architecture '$uname_machine' not supported."
+    exit 1
+fi
+
 # Download and extract
-cometbft_download_url="https://github.com/cometbft/cometbft/releases/download/v${COMETBFT_VERSION}/cometbft_${COMETBFT_VERSION}_linux_amd64.tar.gz"
+cometbft_download_url="https://github.com/cometbft/cometbft/releases/download/v${COMETBFT_VERSION}/cometbft_${COMETBFT_VERSION}_${platform_string}.tar.gz"
 cometbft_temp_dir="$(mktemp -d)"
 pushd "$cometbft_temp_dir" > /dev/null
 curl -sSfL -O "$cometbft_download_url"
-tar -xzf "cometbft_${COMETBFT_VERSION}_linux_amd64.tar.gz" cometbft
+tar -xzf "cometbft_${COMETBFT_VERSION}_${platform_string}.tar.gz" cometbft
 trap 'rm -r "$cometbft_temp_dir"' EXIT
 
 # Try to write to system-wide location.
-if [[ -w /usr/local/bin/ ]] ; then
-    mv -v cometbft /usr/local/bin/
-else
-    cometbft_install_dir="${HOME:?}/bin"
-    >&2 echo "WARNING: /usr/local/bin/ not writable, installing cometbft to $cometbft_install_dir"
-    mkdir -p "$cometbft_install_dir"
+cometbft_install_dir="/usr/local/bin"
+if [[ -w "$cometbft_install_dir" ]] ; then
     mv -v cometbft "${cometbft_install_dir}/"
-    export PATH="$PATH:$cometbft_install_dir"
+else
+    >&2 echo "WARNING: $cometbft_install_dir not writable, will prompt for privileges"
+    sudo mv -v cometbft "${cometbft_install_dir}/"
 fi
 
 # Sanity checks
-echo "Checking that cometbft is installed:"
+>&2 echo "Checking that cometbft is installed:"
 which cometbft
 cometbft version
