docs: how to run relayer via local devnet
Adds some docs on maintenance tasks and common testing procedures.
Links out to information elsewhere, just making it discoverable via the
relayer README.

Refs #465, #2252.

diff --git a/deployments/relayer/generate-configs b/deployments/relayer/generate-configs
--- a/deployments/relayer/generate-configs
+++ b/deployments/relayer/generate-configs
@@ -3,7 +3,7 @@ set -euo pipefail
 
 
 if [[ $# -lt 1 ]] ; then
-    >&2 echo "ERROR: no network declared. Use either 'testnet' or 'preview'."
+    >&2 echo "ERROR: no network declared. Use one of: testnet, preview, or local."
     >&2 echo "Usage: $0 <network>"
     exit 1
 fi
