ci: slightly faster rust checks (#5048)
## Describe your changes

A bit of spring cleaning for the CI suite. These changes aim at faster
run times on PRs, mostly via reusing common tooling, and reducing setup
time. These changes _don't_ affect which tests run, out of an abundance
of caution, because we have ongoing development in a feature branch
right now (#5010).

The longest-running CI check is currently the check-all-features job,
which clocks in at ~14m with these changes. That's an improvement over
the ~20m or so it's been taking on other PRs. For full details on the
changes, see the commit messages; to summarize:

* smoke tests use the existing tooling env
* most checks can now be run locally via a justfile target, e.g. `just
check`, to make CI failures more easily replicable locally
* test names have been reformatted for readability
* the noisy "release" checks are removed from PR runs

Overall the checks seem to complete >5m faster than before, which is
good enough to merge as progress. I'm deferring more substantive changes
like kicking long-running jobs to schedules, rather than on-every-PR,
until we have a chance to observe these improvements over time, and
until after the LQT push.

### Example of CI job display _before_ changes


![pz-gh-ci-before](https://github.com/user-attachments/assets/253f991c-c2c8-400b-9e6e-0e5836c0a373)

### Example of CI job display _after_ changes


![pz-gh-ci-after](https://github.com/user-attachments/assets/66fa4c61-4f24-4a6b-afb5-0e0ee9bee348)


## Issue ticket number and link

N/A 

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the
"consensus-breaking" label. Otherwise, I declare my belief that there
are not consensus-breaking changes, for the following reason:

  > ci and test code only, application logic remains unchanged

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -1,88 +1,19 @@
-name: Rust CI
+name: rust
 on:
   pull_request:
     # Don't run Rust tests if only docs changed.
     paths-ignore:
       - 'docs/**'
+  # Also support ad-hoc calls for workflow.
+  workflow_call:
+  workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  test:
-    name: Test Suite
-    runs-on: buildjet-16vcpu-ubuntu-2204
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          lfs: true
-
-      # The `rust-toolchain.toml` file dictates which version of rust to setup.
-      - name: check rust version
-        run: rustc --version
-
-      - name: Install nextest
-        uses: taiki-e/install-action@nextest
-
-      - name: Load rust cache
-        uses: astriaorg/buildjet-rust-cache@v2.5.1
-
-      - name: Run cargo check, failing on warnings
-        run: cargo check --release --all-targets
-        env:
-          # The `-D warnings` option causes an error on warnings.
-          RUSTFLAGS: "-D warnings"
-
-      - name: Check wasm compatibility
-        run: ./deployments/scripts/check-wasm-compat.sh
-
-      # If a dependency was modified, Cargo.lock may flap if not committed.
-      - name: Check for diffs
-        shell: bash
-        run: |
-          s="$(git status --porcelain)"
-          if [[ -n "$s" ]]; then
-              echo "ERROR: found modified files that should be committed:"
-              echo "$s"
-              git diff | head -n 128
-              exit 1
-          else
-              echo "OK: no uncommitted changes detected"
-          fi
-
-      - name: Run tests with nextest
-        run: cargo nextest run --release
-        env:
-          CARGO_TERM_COLOR: always
-
-  fmt:
-    name: Rustfmt
-    runs-on: buildjet-8vcpu-ubuntu-2204
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          # we don't need lfs for the check to pass, but we do need it for the paths-ignore
-          # option to work correctly.
-          lfs: true
-      - name: Load rust cache
-        uses: astriaorg/buildjet-rust-cache@v2.5.1
-      - run: cargo fmt --all -- --check
-
-  check:
-    name: Check all crate features
-    runs-on: buildjet-16vcpu-ubuntu-2204
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          lfs: true
-      - name: Load rust cache
-        uses: astriaorg/buildjet-rust-cache@v2.5.1
-      - name: install cargo-hack
-        run: cargo install cargo-hack
-      # Build each crate separately, to validate that the feature-gating is working.
-      # This is a lighter-weight version of `cargo check-all-features --workspace --release`.
-      - run: ./deployments/scripts/check-crate-feature-sets
-
-  # Integration tests that run against the public testnet endpoints.
-  # Temporarily enabling these in CI, to provide assurance during refactoring.
-  testnet-integration:
+  lint:
     runs-on: buildjet-16vcpu-ubuntu-2204
     steps:
       - uses: actions/checkout@v4
@@ -102,9 +33,79 @@ jobs:
       - name: Load rust cache
         uses: astriaorg/buildjet-rust-cache@v2.5.1
 
-      # Confirm that the nix devshell is buildable and runs at all.
-      - name: validate nix env
-        run: nix develop --command echo hello
+      # The `rust-toolchain.toml` file dictates which version of rust to setup.
+      - name: check rust version
+        run: nix develop --command rustc --version
 
-      - name: run the testnet integration tests
-        run: nix develop --command just integration-testnet
+      # Run `cargo check`, with a custom target dir for caching.
+      - name: run cargo check
+        run: nix develop --command just check
+
+      # If a dependency was modified, Cargo.lock may flap if not committed.
+      - name: Check for diffs
+        shell: bash
+        run: |
+          s="$(git status --porcelain)"
+          if [[ -n "$s" ]]; then
+              echo "ERROR: found modified files that should be committed:"
+              echo "$s"
+              git diff | head -n 128
+              exit 1
+          else
+              echo "OK: no uncommitted changes detected"
+          fi
+
+  # As of 2025Q1, the "features" job is the slowest in the CI suite.
+  # Consider moving to a scheduled job on main, rather than running on PRs.
+  features:
+    runs-on: buildjet-16vcpu-ubuntu-2204
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          lfs: true
+
+      - name: install nix
+        uses: nixbuild/nix-quick-install-action@v28
+
+      - name: setup nix cache
+        uses: nix-community/cache-nix-action@v5
+        with:
+          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
+          restore-prefixes-first-match: nix-${{ runner.os }}-
+          backend: buildjet
+
+      - name: Load rust cache
+        uses: astriaorg/buildjet-rust-cache@v2.5.1
+
+      # Build each crate separately, to validate that the feature-gating is working.
+      # This is a lighter-weight version of `cargo check-all-features --workspace --release`.
+      - name: check crate features
+        run: nix develop --command ./deployments/scripts/check-crate-feature-sets
+
+      - name: check wasm compatibility
+        run: nix develop --command ./deployments/scripts/check-wasm-compat.sh
+
+  test:
+    runs-on: buildjet-16vcpu-ubuntu-2204
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          lfs: true
+
+      - name: install nix
+        uses: nixbuild/nix-quick-install-action@v28
+
+      - name: setup nix cache
+        uses: nix-community/cache-nix-action@v5
+        with:
+          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
+          restore-prefixes-first-match: nix-${{ runner.os }}-
+          backend: buildjet
+
+      - name: Load rust cache
+        uses: astriaorg/buildjet-rust-cache@v2.5.1
+
+      - name: Run tests with nextest
+        run: nix develop --command just test
+        env:
+          CARGO_TERM_COLOR: always
