pd: rename "testnet" subcommand to "network"
Mostly a cosmetic change, since it's a rename. Requires lots of
carry-over throughout the docs. Kept the internal APIs the same for the
most part. This is a breaking change from the context of node operators,
though, because now pd will look in a different location for info.

diff --git a/deployments/compose/docker-compose.yml b/deployments/compose/docker-compose.yml
--- a/deployments/compose/docker-compose.yml
+++ b/deployments/compose/docker-compose.yml
@@ -1,31 +1,31 @@
----
+
 # docker-compose file for running a Penumbra node.
 # Stores the node config in a docker "volume", which should be
-# reset between testnets: `docker volume rm compose_penumbra-pd-node0` or similar.
-# See docs for details:  https://guide.penumbra.zone/main/pd/join-testnet.html
+# reset between networks: `docker volume rm compose_penumbra-pd-node0` or similar.
+# See docs for details:  https://guide.penumbra.zone/node/pd/join-network.html
 
 # N.B. the "latest" tag for Penumbra container images maps to the latest
 # tagged release; use "main" tag for tracking the rolling preview networks.
 version: "3.7"
 services:
 
-  # Initialize node config, via `pd testnet join`.
+  # Initialize node config, via `pd network join`.
   pd-node0-init:
     image: ghcr.io/penumbra-zone/penumbra:latest
     command: >-
       sh -c
       "
       pd --version &&
-      if ! test -e /pd/testnet_data/node0/cometbft/config/config.toml ; then
-          >&2 printf 'WARN: testnet config not found. Creating fresh node identity.'
-          >&2 echo ' See docs for details: https://guide.penumbra.zone/main/pd/join-testnet.html'
-          /bin/pd testnet --testnet-dir /pd/testnet_data join
+      if ! test -e /pd/network_data/node0/cometbft/config/config.toml ; then
+          >&2 printf 'WARN: network config not found. Creating fresh node identity.'
+          >&2 echo ' See docs for details: https://guide.penumbra.zone/node/pd/join-network.html
+          /bin/pd network --network-dir /pd/network_data join
       else
           >&2 echo 'Node config already found, using it'
       fi &&
-      chown 100 -R /pd/testnet_data/node0/cometbft &&
-      chown 1000 -R /pd/testnet_data/node0/pd &&
-      ls -l /pd/testnet_data/node0/ && exit 0
+      chown 100 -R /pd/network_data/node0/cometbft &&
+      chown 1000 -R /pd/network_data/node0/pd &&
+      ls -l /pd/network_data/node0/ && exit 0
       "
     restart: on-failure
     volumes:
@@ -40,7 +40,7 @@ services:
     # environment:
       # RUST_LOG: h2=off,debug
     command: >-
-      /bin/pd start --home /pd/testnet_data/node0/pd
+      /bin/pd start --home /pd/network_data/node0/pd
       --grpc-bind 0.0.0.0:8080 --abci-bind 0.0.0.0:26658
       --cometbft-addr http://cometbft-node0:26657
     restart: on-failure
@@ -62,7 +62,7 @@ services:
     volumes:
       - penumbra-pd-node0:/cometbft
     environment:
-      CMTHOME: /cometbft/testnet_data/node0/cometbft
+      CMTHOME: /cometbft/network_data/node0/cometbft
     command: start --proxy_app=tcp://pd-node0:26658
     depends_on:
       - pd-node0
