fix: update docker-compose files for improved node configuration and cleanup

diff --git a/deployments/compose/docker-compose.dev.yml b/deployments/compose/docker-compose.dev.yml
--- a/deployments/compose/docker-compose.dev.yml
+++ b/deployments/compose/docker-compose.dev.yml
@@ -3,26 +3,24 @@
 # Stores the node config in a docker "volume", which should be
 # reset between testnets: `docker volume rm compose_penumbra-pd-node0` or similar.
 # See docs for details:  https://guide.penumbra.zone/main/pd/join-testnet.html
-
+#
 # N.B. the "latest" tag for Penumbra container images maps to the latest
 # tagged release; use "main" tag for tracking the rolling preview networks.
-version: "3.7"
 services:
 
   # Initialize node config, via `pd testnet join`.
   pd-node0-init:
-    platform: "linux/amd64"
     image: ghcr.io/penumbra-zone/penumbra:latest
     command: >-
       sh -c
       "
       pd --version &&
       if ! test -e /pd/testnet_data/node0/cometbft/config/config.toml ; then
-          >&2 printf 'WARN: testnet config not found. Creating fresh node identity.'
-          >&2 echo ' See docs for details: https://guide.penumbra.zone/main/pd/join-testnet.html'
-          /bin/pd testnet --testnet-dir /pd/testnet_data generate
+        >&2 printf 'WARN: testnet config not found. Creating fresh node identity.'
+        >&2 echo ' See docs for details: https://guide.penumbra.zone/main/pd/join-testnet.html'
+        /bin/pd testnet --testnet-dir /pd/testnet_data generate
       else
-          >&2 echo 'Node config already found, using it'
+        >&2 echo 'Node config already found, using it'
       fi &&
       chown 100 -R /pd/testnet_data/node0/cometbft &&
       chown 1000 -R /pd/testnet_data/node0/pd &&
@@ -36,10 +34,9 @@ services:
 
   # The Penumbra daemon
   pd-node0:
-    platform: "linux/amd64"
     image: ghcr.io/penumbra-zone/penumbra:latest
-      # consider verbose debugging logs:
-      # environment:
+    # consider verbose debugging logs:
+    # environment:
     # RUST_LOG: h2=off,debug
     command: >-
       /bin/pd start --home /pd/testnet_data/node0/pd
diff --git a/deployments/compose/docker-compose.yml b/deployments/compose/docker-compose.yml
--- a/deployments/compose/docker-compose.yml
+++ b/deployments/compose/docker-compose.yml
@@ -3,37 +3,34 @@
 # Stores the node config in a docker "volume", which should be
 # reset between networks: `docker volume rm compose_penumbra-pd-node0` or similar.
 # See docs for details:  https://guide.penumbra.zone/node/pd/join-network.html
-
+#
 # N.B. the "latest" tag for Penumbra container images maps to the latest
 # tagged release; use "main" tag for tracking the rolling preview networks.
-version: "3.7"
 services:
 
   # Initialize node config, via `pd network join`.
   pd-node0-init:
-    platform: "linux/amd64"
-    # just container
     image: ghcr.io/penumbra-zone/penumbra:local
     command: >-
       sh -c
       "
       pd --version &&
       if ! test -e /pd/network_data/node0/cometbft/config/config.toml ; then
-          >&2 printf 'WARN: network config not found. Creating fresh local network.\n'
-          # --allocation-address is mnemonic 'test test test test test test test test test test test junk' (commonly used in Ethereum)
-          rm -rf /pd/network_data &&
-          /bin/pd network --network-dir /pd/network_data generate --chain-id penumbra-local-devnet --preserve-chain-id --gas-price-simple 0 --unbonding-delay 302400 --epoch-duration 302400 --proposal-voting-blocks 50 --timeout-commit 500ms --allocation-address "penumbra1eu5pnv6qptp2p0aevfc0adjrpd24glz5shey7wvwlg5sp3ffca2zk32cemjd90ughdh7xqplrej9lqzc06337w2scxykjajd2nrtttvmqt6tssr6pmzp283hhte7y4jf6sn2wh"
+        >&2 printf 'WARN: network config not found. Creating fresh local network.\n'
+        # --allocation-address is mnemonic 'test test test test test test test test test test test junk' (commonly used in Ethereum)
+        rm -rf /pd/network_data &&
+        /bin/pd network --network-dir /pd/network_data generate --chain-id penumbra-local-devnet --preserve-chain-id --gas-price-simple 0 --unbonding-delay 302400 --epoch-duration 302400 --proposal-voting-blocks 50 --timeout-commit 500ms --allocation-address "penumbra1eu5pnv6qptp2p0aevfc0adjrpd24glz5shey7wvwlg5sp3ffca2zk32cemjd90ughdh7xqplrej9lqzc06337w2scxykjajd2nrtttvmqt6tssr6pmzp283hhte7y4jf6sn2wh"
       else
-          >&2 echo 'Node config already found, using it'
+        >&2 echo 'Node config already found, using it'
       fi &&
       if test -d /pd/network_data/node0 ; then
-          mkdir -p /pd/network_data/node0/cometbft/data &&
-          chown 100 -R /pd/network_data/node0/cometbft &&
-          chown 1000 -R /pd/network_data/node0/pd &&
-          ls -l /pd/network_data/node0/ && exit 0
+        mkdir -p /pd/network_data/node0/cometbft/data &&
+        chown 100 -R /pd/network_data/node0/cometbft &&
+        chown 1000 -R /pd/network_data/node0/pd &&
+        ls -l /pd/network_data/node0/ && exit 0
       else
-          >&2 echo 'ERROR: network generation failed'
-          exit 1
+        >&2 echo 'ERROR: network generation failed'
+        exit 1
       fi
       "
     restart: on-failure
@@ -44,11 +41,10 @@ services:
 
   # The Penumbra daemon
   pd-node0:
-    platform: "linux/amd64"
     image: ghcr.io/penumbra-zone/penumbra:local
     # consider verbose debugging logs:
     # environment:
-      # RUST_LOG: h2=off,debug
+    # RUST_LOG: h2=off,debug
     command: >-
       /bin/pd start --home /pd/network_data/node0/pd
       --grpc-bind 0.0.0.0:8080 --abci-bind 0.0.0.0:26658
